version: '2.4'
services:
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo-data:/data/db
  
  node-app:
    build: .
    container_name: node-app
    restart: always
    ports:
      - ${PORT}:5000
    volumes:
      - .:/apps/api
      - /apps/api/node_modules  
    depends_on:
      - mongo-db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data: